### ISSUE TITLE
nulpointer exception when using this plugin

### ISSUE THREAD

**Issue by dza89** [gocd/gocd-ldap-authorization-plugin#12]
GoCD Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0).
Plugin version: 3.0.0.0 ++

Getting the following error:
`2020-06-08 10:01:37,494 ERROR [Thread-80] PluginLoader:121 - Failed to load plugin: plugins_work/gocd-ldap-authorization-plugin.jar. Plugin is invalid. Reasons [Class [LdapPlugin] is annotated with @Extension but cannot be registered. Reason: java.lang.NullPointerException.]`

**Comment by kritika-singh3** [comment]
Hello @dza89, thanks for finding the error. We have created an experimental release with the fix [here](https://github.com/gocd/gocd-ldap-authorization-plugin/releases/tag/v4.0.1-6-exp).
Can you please verify that the issue is resolved? Post that we can make a stable release.

**Comment by dza89** [comment]
@kritika-singh3 

Damn that was fast :)
Thanks alot, this version works like a charm.

**Comment by kritika-singh3** [comment]
Good to know. :) I'll make a stable release. Thanks for verifying.
