### ISSUE TITLE
Force refresh

### ISSUE THREAD

**Issue by jcbandelier** [gocd/gocd-ldap-authorization-plugin#55]
There appears to be a delay between the creation of a group in LDAP and the time when the group is available to be added in a pipeline group's permissions.
Is it possible to reduce this delay and/or force a refresh of the LDAP data?

**Comment by arvindsv** [comment]
Not sure, but I would try changing the `go.security.reauthentication.interval` [property](https://github.com/gocd/gocd/blob/2cc19b718a3493d92f3c9e4912288b8187fe0e21/base/src/main/java/com/thoughtworks/go/util/SystemEnvironment.java#L175) and see.

You'll have to change it in wrapper-properties.conf by adding something like:

```
# Change 123 to the right value ...
wrapper.java.additional.123=-Dgo.security.reauthentication.interval=180
``` 

and see if that changes the delay to 3 mins. Note that this will cause all logged-in users to be reauthenticated every 3 mins and will increase the load on the AD server.

**Comment by jcbandelier** [comment]
Thanks for your help.
