### ISSUE TITLE
Update api-ldap-client-api

### ISSUE THREAD

**Issue by netsandbox** [gocd/gocd-ldap-authorization-plugin#56]
Hi,

can you please update `api-ldap-client-api`.
The currently used version 1.0.0 is over 4 years old and contains also a critical security issue:
https://directory.apache.org/api/news.html

**Comment by arvindsv** [comment]
Dependabot has been bringing this up, but some tests seem to be failing: https://github.com/gocd/gocd-ldap-authorization-plugin/pull/50

Happy to accept a PR, if you or someone who uses this wants to submit one.

**Comment by netsandbox** [comment]
Sadly I'm not a java developer, so I think I can't help here.
For me even a master branch checkout fails to build, a v4.0.1-6 checkout builds fine.

**Comment by chadlwilson** [comment]
Fixed in #57
